export const metadata = {
  title: "Blogs list",
  description: "Generated by Blogs list next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children} </>;
}
